CREATE TABLE KHOA (
    MAKHOA VARCHAR(4) PRIMARY KEY,
    TENKHOA VARCHAR(40),
    NGTLAP SMALLDATETIME,
    TRGKHOA CHAR(4)
);

CREATE TABLE GIAOVIEN (
    MAGV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40),
    HOCVI VARCHAR(40),
	HOCHAM VARCHAR(40),
    GIOITINH CHAR(1),
    NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
    HESO MONEY,
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE MONHOC (
    MAMH VARCHAR(10) PRIMARY KEY,
    TENMH VARCHAR(40),
    TCLT TINYINT,
    TCH TINYINT,
    MAKHOA VARCHAR(4),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE DIEUKIEN (
    MAMH VARCHAR(10),
    MAMH_TRUOC VARCHAR(10),
    PRIMARY KEY (MAMH, MAMH_TRUOC),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
);

CREATE TABLE LOP (
    MALOP VARCHAR(10) PRIMARY KEY,
    TENLOP VARCHAR(40),
    SISO INT,
    MAGVCN CHAR(4),
    MAKHOA VARCHAR(4),
    FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE HOCVIEN (
    MAHV CHAR(10) PRIMARY KEY,
    TEN VARCHAR(40),
    GIOITINH CHAR(1),
    NGAYSINH SMALLDATETIME,
    NOISINH VARCHAR(40),
    MALOP VARCHAR(10),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE GIANGDAY (
    MAGV CHAR(4),
    MALOP VARCHAR(10),
    MAMH VARCHAR(10),
	HOCKY VARCHAR(10),
    NAMHOC VARCHAR(10),
    TUNGAY SMALLDATETIME,
    DENNGAY SMALLDATETIME,
    PRIMARY KEY (MAGV, MALOP, MAMH),
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

CREATE TABLE KETQUATHI (
    MAHV CHAR(10),
    MAMH VARCHAR(10),
	LANTHI TINYINT,
    NGTHI SMALLDATETIME,
    DIEM NUMERIC(4,2),
    KQUA CHAR(1),
    PRIMARY KEY (MAHV, MAMH, NGTHI),
    FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);
--3
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIOITINHGV CHECK (GIOITINH IN ('Nam', 'Nu'))

ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_GIOITINHHV CHECK (GIOITINH IN ('Nam', 'Nu'));
--4
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_DIEM CHECK (DIEM BETWEEN 0 AND 10);
--5
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KQUA CHECK ((KQUA='Dat' AND DIEM BETWEEN 5 and 10) OR (KQUA = 'Khong dat' AND DIEM < 5));
--6
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_LANTHI CHECK (LANTHI < 3);
--7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_HKI CHECK (HOCKY BETWEEN 1 AND 3);
--8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_HVI CHECK (HOCVI IN('CN', 'KS', 'Ths','TS','PTS');

